[package]
name = "actix-example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-identity = "0.3.1"
actix-session = "0.4.1"
actix-web = "3.3.2"
env_logger = "0.8.3"
rand = "0.8.3"
